### ISSUE TITLE
Display (img) (Under game mode)

### ISSUE THREAD

**Issue by theodor90** [theodor90/Music-Quiz#7]
IMG = Artist

**Comment by theodor90** [comment]
`[
    {
        "id": "f6",
        "songName": "True Colors",
        "artist": "Cyndi Lauper",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339692325&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    },
    {
        "id": "i9",
        "songName": "One Last Time",
        "artist": "Ariana Grande",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585207&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "h8",
        "songName": "Here Comes The Sun",
        "artist": "The Beatles",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585205&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "g7",
        "songName": "Stayin' Alive",
        "artist": "Bee Gees",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585199&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "e5",
        "songName": "Somebody That I Used To Know",
        "artist": "Gotye",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585190&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "d4",
        "songName": "Don't Stop Believin'",
        "artist": "Journey",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585188&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "c3",
        "songName": "Poker Face",
        "artist": "Lady Gaga",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585181&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "b2",
        "songName": "Material Girl",
        "artist": "Madonna",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585164&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "a1",
        "songName": "Tiny Dancer",
        "artist": "Elton John",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585162&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    },
    {
        "id": "j10",
        "songName": "Mamma Mia",
        "artist": "ABBA",
        "profileImg": "",
        "url": "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/339585147&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"
    }
]`

**Comment by theodor90** [comment]
"id": "f6",
        "songName": "True Colors",
        "artist": "Cyndi Lauper",


        "id": "i9",
        "songName": "One Last Time",
        "artist": "Ariana Grande",


        "id": "h8",
        "songName": "Here Comes The Sun",
        "artist": "The Beatles",

        "id": "g7",
        "songName": "Stayin' Alive",
        "artist": "Bee Gees",

        "id": "e5",
        "songName": "Somebody That I Used To Know",
        "artist": "Gotye",

        "id": "d4",
        "songName": "Don't Stop Believin'",
        "artist": "Journey",

        "id": "c3",
        "songName": "Poker Face",
        "artist": "Lady Gaga",

        "id": "b2",
        "songName": "Material Girl",
        "artist": "Madonna",

        "id": "a1",
        "songName": "Tiny Dancer",
        "artist": "Elton John",

        "id": "j10",
        "songName": "Mamma Mia",
        "artist": "ABBA",

**Comment by ghost** [comment]
finished with , commponnets/ display.js , gmaeface.js , inputfiled.js , answeroption.js , quizdata.json
